# Generated by Django 4.2.5 on 2023-09-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0002_amodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amodel',
            old_name='password',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='amodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
